version: 0.2

phases:
  build:
    commands:
    - ecdotnet 
    - dotnet build -c Release
    - dotnet publish -c Release --no-build -o publish TrialAWSApp.sln
post-build:
    commands:
        - mv ./TrialAWSApp/bin/Release/netstandard2.1/dist ./artifact
        - cp -R ./TrialAWSApp/bin/Release/netstandard2.1/publish/wwwroot/css ./artifact/
    finally:
        - aws s3 cp ./artifact s3://jade-test-bucket-with-blazor -recursive