version: 0.2

phases:
  build:
    commands:
    - echo build started on `date`
    - dotnet restore
    - dotnet publish -c Release -f netstandard2.1

post-build:
    commands:
        - mv ./TrialAWSApp/bin/Release/netstandard2.1/dist ./artifact
        - cp -R ./TrialAWSApp/bin/Release/netstandard2.1/publish/wwwroot/css ./artifact/
    finally:
        - aws s3 cp ./artifact s3://jade-test-bucket-with-blazor -recursive