version: 0.2

phases:
    pre-build:
    commands:
    - echo Restore started on `date`
    - dotnet restore TrialAWSApp.csproj

  build:
    commands:
    - echo build started on `date`
    - dotnet publish --no-restore -c release

post-build:
    commands:
        - mv ./TrialAWSApp/bin/Release/netstandard2.1/dist ./artifact
        - cp -R ./TrialAWSApp/bin/Release/netstandard2.1/publish/wwwroot/css./artifact/
    finally:
        - aws s3 cp ./artifact s3://jade-test-bucket-with-blazor -recursive